name: Testing

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        codespell_pip_version: ['codespell', 'git+https://github.com/codespell-project/codespell.git']

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install codespell via pip using ${{ matrix.codespell_pip_version }}
        run: pip3 --quiet --quiet install ${{ matrix.codespell_pip_version }}

      - name: Install Bats
        run: |
          git clone --quiet https://github.com/bats-core/bats-core.git
          cd bats-core
          git fetch --tags
          # Checkout the latest tag
          git checkout --quiet $(git describe --tags `git rev-list --tags --max-count=1`)
          sudo ./install.sh "/usr/local" > /dev/null

      - name: Run Bats tests
        run: bats "./test"

  run_action:
    name: Test run action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        path: test/testdata
        only_warn: 1
